### ISSUE TITLE
Finalize how skins work

### ISSUE THREAD

**Issue by omundy** [sneakaway-studio/tally-extension#100]
Will they look like this for example?

![image](https://user-images.githubusercontent.com/279945/75101660-dd604b00-55ad-11ea-839b-7c2929f0b435.png)

**Comment by omundy** [comment]
![image](https://user-images.githubusercontent.com/279945/75102748-6da68c00-55be-11ea-812c-dc14f1cf6b48.png)

**Comment by omundy** [comment]
Maybe the pattern is what changes color 

![image](https://user-images.githubusercontent.com/279945/75113265-42518a80-561a-11ea-833b-4fd571da4a33.png)

**Comment by omundy** [comment]
More variations:


![image](https://user-images.githubusercontent.com/279945/76245465-500a3100-6212-11ea-8f3f-fcf4be4975f9.png)

![image](https://user-images.githubusercontent.com/279945/76246106-78465f80-6213-11ea-89bb-8c5ad80d6dd8.png)

^ In both of the above, Tally's body changes to stage colors (magenta, yellow, orange, red) AND the pattern also changes to match the same hue as the stage but slightly different value 

![image](https://user-images.githubusercontent.com/279945/76245541-7203b380-6212-11ea-9d05-27bde67545ff.png)

^ Tally's body stays magenta but the pattern changes to match the same hue (magenta, yellow, orange, red) as the stage but slightly different value

**Comment by omundy** [comment]
Also, there's this to consider: 

![image](https://user-images.githubusercontent.com/279945/76247921-b4c78a80-6216-11ea-8760-a603cabf5c6e.png)

**Comment by omundy** [comment]
Tally incognito w/ large houndstooth

![image](https://user-images.githubusercontent.com/279945/76317805-235a2600-62b3-11ea-994f-4922b4ba195a.png)

**Comment by omundy** [comment]
Testing some of these with different gradients in code

![image](https://user-images.githubusercontent.com/279945/76339605-b3f32f00-62d0-11ea-93c7-742a3cef5092.png)
![image](https://user-images.githubusercontent.com/279945/76339657-c66d6880-62d0-11ea-9e49-06e543a7c3d8.png)
![image](https://user-images.githubusercontent.com/279945/76339707-d6854800-62d0-11ea-9f12-45e8d675ade6.png)

**Comment by jakecarver** [comment]
A few comments: 

The skin patterns look great. 

For the color changes, I think I'd need to see a gif of the change before I can form an opinion. There should be some sort of transition between skins--going from magenta to yellow suddenly would be jarring. Not sure how we would do that though. Maybe only have the color change be between two colors for the sake of simplicity?

I really like the gradients. They make each skin pop out a lot more than with one color. It also gives us a lot more options for skins (if there are N number of colors for skins, there are N^2 possibilities for gradients of two colors).

The glasses are great, and I like the concept of the incognito shades. However, the shades completely cover Tally's eyes, so she will be a lot less expressive to the user. Not sure what the fix is... Groucho Marx glasses might be funny!

**Comment by omundy** [comment]
> For the color changes, I think I'd need to see a gif of the change before I can form an opinion. There should be some sort of transition between skins--going from magenta to yellow suddenly would be jarring. Not sure how we would do that though. Maybe only have the color change be between two colors for the sake of simplicity?

The solid colors can transition (animate) but the gradients cannot.

> I really like the gradients. They make each skin pop out a lot more than with one color. It also gives us a lot more options for skins (if there are N number of colors for skins, there are N^2 possibilities for gradients of two colors).

Yeah, I like them too. Though I'm not sure how they fit in to the game because the colors currently communicate how close a monster is. @DLammens point out too that the gradients are a substantial visual difference from all the flat colors we use currently in the game.

> The glasses are great, and I like the concept of the incognito shades. However, the shades completely cover Tally's eyes, so she will be a lot less expressive to the user. Not sure what the fix is... Groucho Marx glasses might be funny!

Yes, can lighten. OMG, that's a great idea!

![image](https://user-images.githubusercontent.com/279945/76448479-c8066180-63a0-11ea-9a8c-1428affb23c6.png)

**Comment by omundy** [comment]
Conversation:

- Color changes from magenta to red only. And it's a red gradient instead.
- Skin "algorithm" has in-game effects. Achievements?
- Sunglasses = stealth mode
- Marx glasses are worn when she has blocked a tracker on that website.
- 3d glasses = when she's battle a 3d monster

**Comment by omundy** [comment]
I like this example where you pick your avatar before you start 
![image](https://user-images.githubusercontent.com/279945/83946821-2943a280-a7e1-11ea-83c0-1a82fc3afc95.png)
