### ISSUE TITLE
Stop missing so much in attacks

### ISSUE THREAD

**Issue by jdietrick** [sneakaway-studio/tally-extension#108]

**Comment by jdietrick** [comment]
Tally should tell the user on the first time why they missed.

**Comment by omundy** [comment]
@DLammens for discussion: We fought a monster and Tally missed three times in a row with three different attacks. We should tell the user why this is happening. And, probably want to vary it a little so it's not so often. Something like no more than 2 per battle?

**Comment by omundy** [comment]
@DLammens adding a "randomizer" did the trick 
![image](https://user-images.githubusercontent.com/279945/76236699-72e11900-6203-11ea-95b1-f5ea2c4ff22e.png)
