### ISSUE TITLE
Hide attack buttons after click

### ISSUE THREAD

**Issue by jdietrick** [sneakaway-studio/tally-extension#109]
Tally should tell them what an attack is and what a defense is on the first battle.

**Comment by jdietrick** [comment]
Tally should also tell them how to collect and manage attacks.

**Comment by omundy** [comment]
@jdietrick I moved these Dialogue suggestions to [issue #78](https://github.com/sneakaway-studio/tally-extension/issues/78)

I fixed the usability problem by showing the attack buttons disabled immediately after the player chooses one
![image](https://user-images.githubusercontent.com/279945/79763206-c447f200-82f1-11ea-9a94-7ca0f31df1cf.png)
![image](https://user-images.githubusercontent.com/279945/79763293-e2aded80-82f1-11ea-99ce-b4bbd00c0cef.png)
