### ISSUE TITLE
Battle issues to address

### ISSUE THREAD

**Issue by omundy** [sneakaway-studio/tally-extension#130]
Issues from @DLammens 

- [x]  Notes of tally "weirdness"
  - [x] Can play before logged in, with what?
  - [x] Potenially Labor intensive? Laptop fans came on on startup.
  - [x] Preference for monsters appearing lower on page?
  - [x] http://prntscr.com/r6xpr7 *stats*
	
- [x] Fix Math issues.
  - [x] You can use "false" attacks (before login)
  - [x] Communication Noise definitely is annoying
  - [x] Music Fails to Loop after 30 secs
  - [x] http://prntscr.com/s7j0ki Math doesn't line up.
  - [x] http://prntscr.com/s7j1ar Increase in Defense and Evasion not Displayed
  - [x] http://prntscr.com/s7j20s Texture does not display
  - [x] Evasion too strong
  - [x] http://prntscr.com/s7jfzm
  - [x] http://prntscr.com/s7jgcm Stamina Loss is an instant win, and still outputs battle info without user input.
  - [x] Gains in stats are nearly doubling the stat
  - [x] Needs to give indication of what to do upon loss.
  - [x] Health and Stamina losses being proportional doesn't make sense
  - [x] Confirm that losing other stats (accuracy, attack, defense, evasion) is actually reflected in the dropdown

**Comment by omundy** [comment]
Address this error Windows/Chrome 
![image](https://user-images.githubusercontent.com/279945/92935425-c3396d80-f416-11ea-93ac-727a65a51860.png)

**Comment by DLammens** [comment]
- [ ] Option to disable click sound?

**Comment by DLammens** [comment]
- [ ] Page still shifts "up" when attack anims play

- [ ] Rare case: starts battle with it being the monsters turn, but the monster does not make a move, so the player is trapped.

**Comment by DLammens** [comment]
- [ ] Earned New Badge Prompt Comes up over and over again

**Comment by DLammens** [comment]
Where does updateDisplay get called? Stats aren't updating within the battle, only outside of it.

How does one manage cosmetics?

**Comment by DLammens** [comment]
Tally goes Red but notification does not display.

**Comment by DLammens** [comment]
doAttack in battle-attack does not account for other stat changes due to an attack.

**Comment by DLammens** [comment]
- [ ] Change attacks to reflect attack and defense stats, rather than just max health

**Comment by omundy** [comment]
> * [ ]  Earned New Badge Prompt Comes up over and over again

Is this still an issue? I worked on it a bit ago.

**Comment by DLammens** [comment]
> 
> 
>     * [x]  Change attacks to reflect attack and defense stats, rather than just max health

I haven't experienced it in a while, so I don't think so.

**Comment by DLammens** [comment]
- Recurring issue of monster image frame not placing above page contents. Normally fixes itself after waiting a while

- 

> 
> 
> > * [ ]   Earned New Badge Prompt Comes up over and over again
> 
> Is this still an issue? I worked on it a bit ago.
Shouldn't be, I tested it and the badge didn't pop up again.
