### ISSUE TITLE
Add points to score by capturing monster

### ISSUE THREAD

**Issue by tucraig** [sneakaway-studio/tally-extension#29]
The score should be tied to monster encounters, on top of clicking certain elements of the web.

If the user has not encountered a monster of this mid before, it should set the points the user should receive to 100, otherwise the user should just get 50 per monster. That way you are awarded double for your first encounter and the points for roughly 10 clicks of elements would equate to 1 monster.

**Comment by omundy** [comment]
@tucraig it took a while but I just added this to the game ;-)
