### ISSUE TITLE
Write more diverse Tally dialogue

### ISSUE THREAD

**Issue by omundy** [sneakaway-studio/tally-extension#78]
Add to the Dialogue spreadsheet:
- [x] Explain battle progress
- [x] Tally should also tell them how to collect and manage attacks.
- [x] Tally should tell them what an attack is and what a defense is on the first battle.

**Comment by omundy** [comment]
@jakecarver Can you read this article? [How Companies Learn Your Secrets](https://www.nytimes.com/2012/02/19/magazine/shopping-habits.html?pagewanted=all&_r=0) Let's discuss making Tally offer to tell players creepy data privacy stories. Think you could condense the Target pregnancy story in the NYT article into 10-15 lines? Check out `line 102` in the [spreadsheet](https://docs.google.com/spreadsheets/d/17V-efNqn3Czp3KfSIR7xxJhHiW_921YLMK8j-CZoW_U/edit#gid=0)

**Comment by jakecarver** [comment]
Uploaded this:

Corporations can learn a lot about you just by your buying habits--like whether you're pregnant or not. Target found that pregnant women often buy specific products at different points in their pregnancy. Within the first 20 weeks of pregnancy, women tend to buy supplements like calcium, magnesium, and zinc. Pregnent women also tend to buy unscented lotion in their second trimester. Using about 25 buying habits like these, Target can not only predict if someone is pregnant, but what stage of pregnancy someone is at and send them targeted ads.

**Comment by omundy** [comment]
Excellent! I broke it down to [singular phrases](https://docs.google.com/spreadsheets/d/17V-efNqn3Czp3KfSIR7xxJhHiW_921YLMK8j-CZoW_U/edit#gid=0) but they're a little long. Could you make them more bite-size so the character count keeps them from wrapping. *If they are too long then it takes too long to read I think.

**Comment by omundy** [comment]
Notes on the player's relationship to Tally

- Tally is the player's companion
- She is intelligent
- She is listening to your instructions and then follows them (e.g. you click on a cookie, or choose an attack in battle)
- It is her health, not our health
- Tally lives in the computer, but can break the 4th wall to tell you about it ("there are monsters here")

**Comment by jakecarver** [comment]
How are we going to handle product monster a/an? Is there a way to tell if the name of a product monster begins with a vowel or not, and can we choose dialogue accordingly?

Also, the subcategory "greetings" appears randomly at any time. Shouldn't that only be when the game is launched? Maybe we can have a new subcategory "conversation" where Tally can crack a joke or say some character-building stuff.

**Comment by omundy** [comment]
https://github.com/sneakaway-studio/tally-extension/blob/master/assets/js/content/dialogue.js

**Comment by omundy** [comment]
@jakecarver I'm enjoying the new dialogue you added! I added some additional suggestions for Dialogue in the issue above.
